version: "3.9"

services:
  bingesentry:
    image: bingesentry:latest
    container_name: bingesentry
    user: "1000:1000"
    environment:
     - TZ=America/New_York
     - RCLONE_CONFIG=/app/config/rclone.conf
    volumes:
     - /media/docker/data/bingesentry:/app/config
     - /opt/altmount/config/rclone/rclone.conf:/app/config/rclone.conf
     - /mnt:/mnt
